# Generated by Django 3.0.3 on 2020-02-15 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nickname', models.CharField(help_text='Enter a nickname', max_length=25, unique=True, verbose_name='Nickname')),
                ('email', models.EmailField(help_text='Enter Valid Email ID', max_length=100, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(help_text='Enter Your First Name', max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, default='', help_text='Enter Your Last Name', max_length=255, verbose_name='Last Name')),
                ('slug', models.SlugField(default='', max_length=255, unique=True, verbose_name='Slug')),
                ('country', models.CharField(blank=True, default='', max_length=100, verbose_name='Country')),
                ('ip_address', models.CharField(blank=True, default='', max_length=35, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, default='', max_length=255, verbose_name='User Agent')),
                ('image', models.ImageField(blank=True, default='default.png', help_text='Upload Your Profile Pic', upload_to='users', verbose_name='Image')),
                ('email_sent', models.BooleanField(blank=True, default=False, null=True, verbose_name='Email Sent')),
                ('activation_deadline', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Activation Deadline')),
                ('activation_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Activation Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is Superuser')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Joined')),
            ],
            options={
                'verbose_name': 'Registered User',
                'verbose_name_plural': 'Registered Users',
            },
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, default='', max_length=20, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, default='', max_length=255, verbose_name='User Agent')),
                ('country', models.CharField(blank=True, default='', max_length=50, verbose_name='Country')),
                ('city', models.CharField(blank=True, default='', max_length=50, verbose_name='City')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoggedInUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=32, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logged_in_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
