# Generated by Django 3.0.4 on 2020-03-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='Hot Post'),
        ),
        migrations.DeleteModel(
            name='TrendingPost',
        ),
    ]
